apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-data-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Only one pod may be scheduled to use this volume
  storageClassName: local-storage
  local:
    path: /var/clickhouse

  nodeAffinity: 
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - test-cluster-1-worker
              - test-cluster-1-worker2
---
apiVersion: v1
kind: Pod
metadata:
  name: clickhouse-1
  labels:
    app: clickhouse
spec:
  containers:
    - name: clickhouse
      image: clickhouse:lts-jammy
