kind: Cluster
name: test-cluster-1
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
      # - containerPort: 5000
      #   hostPort: 5000
      #   # optional: set the bind address on the host
      #   # 0.0.0.0 is the current default
      #   listenAddress: "127.0.0.1"
      #   # optional: set the protocol to one of TCP, UDP, SCTP.
      #   # TCP is the default
      #   protocol: TCP
- role: worker
  extraMounts:
    - hostPath: /home/eric/Projects/HealthInsightReplacement/kubernetes/persistent-volume
      containerPath: /db-volume
- role: worker
- role: worker

# networking:
#   ipFamily: ipv4
#   networkName: "test-cluster-1"
