[package]
name = "try_fhir_sdk"
version = "0.1.0"
edition = "2024"

[dependencies]

clickhouse = "0.13.2"
fhir-model = { version = "0.12.0", features = ["r4b"], default-features = false}
serde = "1.0.219"
serde_json = "1.0.140"
